name: Keep Workflow Alive
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create empty commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit --allow-empty -m "Keep workflow alive"
          git push
